// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file diffy/v1/diffy.proto (package diffy.v1, syntax proto3)
/* eslint-disable */

import { DemoService } from "./diffy_pb";

/**
 * @generated from rpc diffy.v1.DemoService.GetGreeting
 */
export const getGreeting = DemoService.method.getGreeting;
