// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file diffy/v1/diffy.proto (package diffy.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file diffy/v1/diffy.proto.
 */
export const file_diffy_v1_diffy: GenFile = /*@__PURE__*/
  fileDesc("ChRkaWZmeS92MS9kaWZmeS5wcm90bxIIZGlmZnkudjEiMwoSR2V0R3JlZXRpbmdSZXF1ZXN0EgwKBG5hbWUYASABKAkSDwoHYXR0ZW1wdBgCIAEoBSJXChNHZXRHcmVldGluZ1Jlc3BvbnNlEg8KB21lc3NhZ2UYASABKAkSEQoJc2VydmVkX2J5GAIgASgJEhwKFGdlbmVyYXRlZF9hdF91bml4X21zGAMgASgDMlkKC0RlbW9TZXJ2aWNlEkoKC0dldEdyZWV0aW5nEhwuZGlmZnkudjEuR2V0R3JlZXRpbmdSZXF1ZXN0Gh0uZGlmZnkudjEuR2V0R3JlZXRpbmdSZXNwb25zZWIGcHJvdG8z");

/**
 * @generated from message diffy.v1.GetGreetingRequest
 */
export type GetGreetingRequest = Message<"diffy.v1.GetGreetingRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: int32 attempt = 2;
   */
  attempt: number;
};

/**
 * Describes the message diffy.v1.GetGreetingRequest.
 * Use `create(GetGreetingRequestSchema)` to create a new message.
 */
export const GetGreetingRequestSchema: GenMessage<GetGreetingRequest> = /*@__PURE__*/
  messageDesc(file_diffy_v1_diffy, 0);

/**
 * @generated from message diffy.v1.GetGreetingResponse
 */
export type GetGreetingResponse = Message<"diffy.v1.GetGreetingResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: string served_by = 2;
   */
  servedBy: string;

  /**
   * @generated from field: int64 generated_at_unix_ms = 3;
   */
  generatedAtUnixMs: bigint;
};

/**
 * Describes the message diffy.v1.GetGreetingResponse.
 * Use `create(GetGreetingResponseSchema)` to create a new message.
 */
export const GetGreetingResponseSchema: GenMessage<GetGreetingResponse> = /*@__PURE__*/
  messageDesc(file_diffy_v1_diffy, 1);

/**
 * @generated from service diffy.v1.DemoService
 */
export const DemoService: GenService<{
  /**
   * @generated from rpc diffy.v1.DemoService.GetGreeting
   */
  getGreeting: {
    methodKind: "unary";
    input: typeof GetGreetingRequestSchema;
    output: typeof GetGreetingResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_diffy_v1_diffy, 0);

